#page title
page_title: "Plant Swap - Blossm"                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
page_desc: "Plant Swap App"

# App Info
ios_app_id: 1503863325                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
android_app_id: 4972386032729837269
appstore_link: "https://apps.apple.com/us/app/id1503863325"
playstore_link: "https://play.google.com/store/apps/details?id=garden.blossm"
presskit_download_link:                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: /assets/img/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_logo: /assets/img/logo.png
app_name: Blossm - Plant Swap                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price:                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: "We want to revolutionize the way you connect to people in the community through a shared passion of plants. Our team of quirky green-thumbed enthusiasts have dedicated an immense amount of time and effort to create a way to do this. We hope you will fulfill all your horticultural desires and make this world a greener place!"

enable_smart_app_banner: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
port: 8080

# Build settings
#theme: minima
plugins:
  - jekyll-sitemap

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
