#page title
page_title: "Social Plant Market - Blossm"                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
page_desc: "Social Plant Marketplace App"

# App Info
ios_app_id: 1503863325                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
android_app_id: 4972386032729837269
appstore_link: "https://apps.apple.com/us/app/id1503863325"
playstore_link: "https://play.google.com/store/apps/details?id=garden.blossm"
presskit_download_link:                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: /assets/img/ios_app_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_logo: /assets/img/logo.png
app_name: Blossm - Social Plant Marketplace                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_name_short: Blossm
app_price:                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Social Plant Marketplace App

enable_smart_app_banner: true                                      # Set to true to show a smart app banner at top of page on mobile devices.


email_address: info@blossm.garden
facebook_username: blossmplantswap
instagram_username: blossmplantswap
tiktok_username: blossmplantswap

# Site Data
browse_plants: Browse Plants
browse_plants_description: Search through the market locally and nationally to browse plants and find
  ones you like!
buy_sell_swap: Buy, Sell or Swap
buy_sell_swap_description: Find new plants to buy or sell and swap plants of your
  own on our market!
socialize: Socialize With Our Community
socialize_description: Chat and connect with fellow plant enthusiasts in your neighborhood and beyond.
  Share planty advice, give some plant ID help, and even show off your favorite plant!
town: Ocean Beach
city: San Diego, CA 92107
team_description: One of the most rewarding experiences is using Blossm ourselves & meeting so many awesome people!
  Blossm was born from a desire to meet like-minded folk who enjoy growing their own food, treating their plants like their babies,
  nerding out on optimal propagation techniques & just wanting to share the knowledge they've learned over the years.
mission: We want to revolutionize the way you connect to people in the community through
  a shared passion of plants. Our team of quirky green-thumbed enthusiasts have dedicated an immense
  amount of time and effort to create a way to do this. We hope you will fulfill all your
  horticultural desires and make this world a greener place!

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.0
topbar_title_color: "#ffffff"

cover_image:                    # Replace with alternative image path or image URL.
cover_overlay_color: "#079365"
cover_overlay_transparency: 1

device_color: black
device_android_color: android-black    # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#079365"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#ffffff"
social_icons_background_color: "#000000"

footer_text_color: "#666666"


port: 8080

collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
#theme: minima
plugins:
  - jekyll-sitemap

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
